name: Fudan Daily

on:
  schedule:
    - cron: '49 15 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Prepare environment
        run: pip install beautifulsoup4 lxml requests
      - name: Run app
        run: python fudanDaily.py
        env:
          USERNAME: ${{ secrets.USERNAME1 }}
          PASSWORD: ${{ secrets.PASSWORD1 }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
